# Checklist {#sp-list}



```{r loadPack, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(mapview)
library(raster)
library(shiny)
library(ggplot2)
library(leaflet)
```


```{r loadData, echo=FALSE, message=FALSE, warning=FALSE}

ST <- st_read("ST_cast.shp", quiet = TRUE)
P <- st_read("P_cast.shp", quiet = TRUE)
protected_areas <- st_read("obo_np_stp.shp", quiet = TRUE)

combined_dataset <- 
  readxl::read_excel("combined_dataset_2021-10-21.xlsx")

endemic_list <-
  combined_dataset %>%
  filter(EndemicTS == "E") %>%
  dplyr::select(
    idtax_f,
    tax_infra_level,
    tax_fam,
    tax_gen,
    tax_famclass,
    starts_with("traitvalue"),
    taxo_unclear,
    status_revision_needed
  ) %>%
  distinct() %>%
  arrange(tax_fam, tax_infra_level)

```

```{r species1, echo=FALSE, message=FALSE, warning=FALSE}

id_sp <- endemic_list$idtax_f[1]

combined_dataset_sf <- 
  combined_dataset %>%
  filter(georef_final == 1, idtax_f == id_sp) %>%
  st_as_sf(coords = c("ddlon", "ddlat"))

st_crs(combined_dataset_sf) <- 4326

```


## *`r  endemic_list$tax_infra_level[1]`*

[*`r  endemic_list$tax_infra_level[1]`*](https://tropicos.org/name/100299918)

```{r echo=FALSE, message=FALSE, warning=FALSE}


map_ST <- 
  ggplot() +
  geom_sf(
    data = P,
    fill = "lightgrey",
    color = "black",
    lwd = NA
  ) +
  ggspatial::annotation_map_tile(type = "hotstyle",
                                 zoom = 12, 
                                 cachedir = system.file("rosm.cache", package = "ggspatial")) +
  labs(y= " ", x = " ") +
  scale_x_continuous(limits = c(6.45, 6.8)) +
  scale_y_continuous(limits = c(0, 0.41)) +
    ggsn::scalebar(dist = 5, dist_unit = "km",
                   transform = TRUE, model = "WGS84", 
                   x.min = 6.47, x.max = 6.55, 
                   y.min = 0.39, y.max = 0.409, 
                 st.dist = 1, height = 0.3) +
    geom_sf(data = protected_areas,
          fill = NA,
          color = "red",
          lwd = 0.5)

if (length(unique(combined_dataset_sf$extirpated)) > 1) {
  
  map_ST <- 
    map_ST +
      geom_sf(
    data = combined_dataset_sf %>% 
      mutate(extirpated = as.character(extirpated)),
    mapping = aes(color = extirpated)
  ) +
  scale_color_manual(name = " ", 
                    values = c("black", "red"),
                    labels = c("Occurrence representing a \nsubpopulation still present",
                               "Likely \nextirpated occurence")) +
  theme(panel.background = element_rect(fill = "white", colour = NA),
        legend.background = element_rect(fill = NA, colour = NA),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(1,"line"),
        legend.position = c(0.7, 0.12),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.text = element_text(
    margin = margin(l = 10, unit = "pt")),
    legend.key.height = unit(1,"line"))
  
} else {
  
    map_ST <- 
    map_ST +
      geom_sf(
    data = combined_dataset_sf
  )
  
  
}


png(paste0(gsub(" ", "_", endemic_list$tax_infra_level[1]), "_", "ST", ".png"), 
    width = 30, height = 15, units = "cm", res = 400)
map_ST
dev.off()


map_lf <- 
  leaflet() %>%
  addProviderTiles(providers$OpenStreetMap, group =  "Open Street Map") %>%
  addProviderTiles(providers$Esri.WorldImagery, group =  "Esri") %>%
  # leaflet::addPolygons(data = st_transform(params$aoo_sf, 4326),
  #                      fillColor = "blue",
  #                      weight = 1,
  #                      opacity = 0.4,
  #                      color = "blue",
  #                      dashArray = "1",
  #                      fillOpacity = 0.4,
  #                      group = "AOO",
  #                      label = "AOO") %>%
  addMarkers(data = combined_dataset_sf,
             popup = leafpop::popupTable(combined_dataset_sf %>% 
                                           dplyr::select(colnam, nbr, coly, loc_notes, habitat) %>% 
                                           sf::st_set_geometry(NULL)),
             group = "Transects",
             clusterOptions = markerClusterOptions())

  htmlwidgets::saveWidget(map_lf, "leaflet.html")
  # browseURL("leaflet.html")
  file.rename("leaflet.html", "D:/MonDossierR/stp_website_backup/static/img/leaflet.html")

  # m = leaflet(data = cycle_hire) %>%
  #   addProviderTiles(providers$CartoDB.Positron) %>%
  #   addCircles(col = ~pal(nbikes), opacity = 0.9) %>%
  #   addPolygons(data = lnd, fill = FALSE) %>%
  #   addLegend(pal = pal, values = ~nbikes) %>%
  #   setView(lng = -0.1, 51.5, zoom = 12) %>%
  #   addMiniMap()

```


```{r fig.show='asis', echo=FALSE, results='asis', message=FALSE, warning=FALSE}

map_ST

```


```{r leaflet, echo=FALSE, message=FALSE, warning=FALSE}
knitr::include_url("https://cepf-stp-threat-flora.netlify.app/img/leaflet")
```


```{r imgTrop, echo=FALSE, message=FALSE, warning=FALSE}
knitr::include_url("http://legacy.tropicos.org/ImageFullView.aspx?imageid=100793776")
```




```{r eval=FALSE}



sampling_records_grid_A <- 
  ggplot() +
  geom_sf(
    data = A,
    fill = "lightgrey",
    color = "black",
    lwd = NA
  ) +
  ggspatial::annotation_map_tile(zoom = 13, cachedir = system.file("rosm.cache", package = "ggspatial")) +
  geom_sf(data = protected_areas,
          fill = NA,
          color = "red",
          lwd = 1) +
  ggtitle(label = "a)") +
  labs(y= " ", x = " ") +
  geom_sf(data = grid_completed_A %>% 
            filter(!is.na(n)), mapping = aes(fill = n)) +
  scale_fill_viridis_c(name = "Number of \nrecords", direction = -1, alpha = 0.5, option = "plasma") +
  scale_x_continuous(limits = c(5.61, 5.68)) +
  scale_y_continuous(limits = c(-1.49, -1.4)) +
  theme(panel.background = element_rect(fill = "white", colour = NA),
        legend.background = element_rect(fill = NA, colour = NA),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12, face = "bold"),
        legend.key.size = unit(1,"line"),
        legend.position = c(0.8, 0.2),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
    ggsn::scalebar(dist = 1, dist_unit = "km",
                   transform = TRUE, model = "WGS84", 
                   x.min = 5.61, x.max = 5.63, y.min = -1.481, y.max = -1.44, 
                 st.dist = 0.1)





```






